from sqlalchemy import (
    Column, Integer, BigInteger, String, Date, DateTime, Text, BINARY, SmallInteger, DECIMAL
)
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()

class PatientData(Base):
    __tablename__ = "patient_data"

    id = Column(BigInteger, primary_key=True, autoincrement=True)
    uuid = Column(BINARY(16), unique=True, nullable=True)
    title = Column(String(255), nullable=False)
    language = Column(String(255), nullable=False)
    financial = Column(String(255), nullable=False)
    fname = Column(String(255), nullable=False)
    lname = Column(String(255), nullable=False)
    mname = Column(String(255), nullable=False)
    DOB = Column(Date, nullable=True)
    street = Column(String(255), nullable=False)
    postal_code = Column(String(255), nullable=False)
    city = Column(String(255), nullable=False)
    state = Column(String(255), nullable=False)
    country_code = Column(String(255), nullable=False)
    drivers_license = Column(String(255), nullable=False)
    ss = Column(String(255), nullable=False)
    occupation = Column(Text, nullable=True)
    phone_home = Column(String(255), nullable=False)
    phone_biz = Column(String(255), nullable=False)
    phone_contact = Column(String(255), nullable=False)
    phone_cell = Column(String(255), nullable=False)
    pharmacy_id = Column(Integer, nullable=False, default=0)
    status = Column(String(255), nullable=False)
    contact_relationship = Column(String(255), nullable=False)
    date = Column(DateTime, nullable=True)
    sex = Column(String(255), nullable=False)
    referrer = Column(String(255), nullable=False)
    referrerID = Column(String(255), nullable=False)
    providerID = Column(Integer, nullable=True)
    ref_providerID = Column(Integer, nullable=True)
    email = Column(String(255), nullable=True)
    email_direct = Column(String(255), nullable=False)
    ethnoracial = Column(String(255), nullable=False)
    race = Column(String(255), nullable=False)
    ethnicity = Column(String(255), nullable=False)
    religion = Column(String(40), nullable=False)
    interpretter = Column(String(255), nullable=False)
    migrantseasonal = Column(String(255), nullable=False)
    family_size = Column(String(255), nullable=False)
    monthly_income = Column(String(255), nullable=False)
    billing_note = Column(Text, nullable=True)
    homeless = Column(String(255), nullable=False)
    financial_review = Column(DateTime, nullable=True)
    pubpid = Column(String(255), nullable=False)
    pid = Column(BigInteger, nullable=False, primary_key=True, default=0)
    genericname1 = Column(String(255), nullable=False)
    genericval1 = Column(String(255), nullable=False)
    genericname2 = Column(String(255), nullable=False)
    genericval2 = Column(String(255), nullable=False)
    hipaa_mail = Column(String(3), nullable=False)
    hipaa_voice = Column(String(3), nullable=False)
    hipaa_notice = Column(String(3), nullable=False)
    hipaa_message = Column(String(20), nullable=False)
    hipaa_allowsms = Column(String(3), nullable=False, default="NO")
    hipaa_allowemail = Column(String(3), nullable=False, default="NO")
    squad = Column(String(32), nullable=False)
    fitness = Column(Integer, nullable=False, default=0)
    referral_source = Column(String(30), nullable=False)
    usertext1 = Column(String(255), nullable=False)
    usertext2 = Column(String(255), nullable=False)
    usertext3 = Column(String(255), nullable=False)
    usertext4 = Column(String(255), nullable=False)
    usertext5 = Column(String(255), nullable=False)
    usertext6 = Column(String(255), nullable=False)
    usertext7 = Column(String(255), nullable=False)
    usertext8 = Column(String(255), nullable=False)
    userlist1 = Column(String(255), nullable=False)
    userlist2 = Column(String(255), nullable=False)
    userlist3 = Column(String(255), nullable=False)
    userlist4 = Column(String(255), nullable=False)
    userlist5 = Column(String(255), nullable=False)
    userlist6 = Column(String(255), nullable=False)
    userlist7 = Column(String(255), nullable=False)
    pricelevel = Column(String(255), nullable=False, default="standard")
    regdate = Column(DateTime, nullable=True)
    contrastart = Column(Date, nullable=True)
    completed_ad = Column(String(3), nullable=False, default="NO")
    ad_reviewed = Column(Date, nullable=True)
    vfc = Column(String(255), nullable=False)
    mothersname = Column(String(255), nullable=False)
    guardiansname = Column(Text, nullable=True)
    allow_imm_reg_use = Column(String(255), nullable=False)
    allow_imm_info_share = Column(String(255), nullable=False)
    allow_health_info_ex = Column(String(255), nullable=False)
    allow_patient_portal = Column(String(31), nullable=False)
    deceased_date = Column(DateTime, nullable=True)
    deceased_reason = Column(String(255), nullable=False)
    soap_import_status = Column(SmallInteger, nullable=True)
    cmsportal_login = Column(String(60), nullable=False)
    care_team_provider = Column(Text, nullable=True)
    care_team_facility = Column(Text, nullable=True)
    care_team_status = Column(Text, nullable=True)
    county = Column(String(40), nullable=False)
    industry = Column(Text, nullable=True)
    imm_reg_status = Column(Text, nullable=True)
    imm_reg_stat_effdate = Column(Text, nullable=True)
    publicity_code = Column(Text, nullable=True)
    publ_code_eff_date = Column(Text, nullable=True)
    protect_indicator = Column(Text, nullable=True)
    prot_indi_effdate = Column(Text, nullable=True)
    guardianrelationship = Column(Text, nullable=True)
    guardiansex = Column(Text, nullable=True)
    guardianaddress = Column(Text, nullable=True)
    guardiancity = Column(Text, nullable=True)
    guardianstate = Column(Text, nullable=True)
    guardianpostalcode = Column(Text, nullable=True)
    guardiancountry = Column(Text, nullable=True)
    guardianphone = Column(Text, nullable=True)
    guardianworkphone = Column(Text, nullable=True)
    guardianemail = Column(Text, nullable=True)
    sexual_orientation = Column(Text, nullable=True)
    gender_identity = Column(Text, nullable=True)
    birth_fname = Column(Text, nullable=True)
    birth_lname = Column(Text, nullable=True)
    birth_mname = Column(Text, nullable=True)
    dupscore = Column(Integer, nullable=False, default=-9)
    name_history = Column(Text, nullable=True)
    suffix = Column(Text, nullable=True)
    street_line_2 = Column(Text, nullable=True)
    patient_groups = Column(Text, nullable=True)
    prevent_portal_apps = Column(Text, nullable=True)
    provider_since_date = Column(Text, nullable=True)
    created_by = Column(BigInteger, nullable=True)
    updated_by = Column(BigInteger, nullable=True)
    ambrosiasys_email = Column(Text, nullable=True)
    ambrosiasys_password = Column(Text, nullable=True)
    ambrosiasys_signature = Column(Text, nullable=True)
    device_id1 = Column(Text, nullable=True)
    device_id2 = Column(Text, nullable=True)
    googlefit_email = Column(String(255), nullable=True)
    tidepull_email = Column(String(255), nullable=True)
    tidepull_password = Column(String(255), nullable=True)
    marsonik_status = Column(Integer, nullable=True)
    marsonik_gateway_id = Column(String(100), nullable=True)
    ncr = Column(Text, nullable=True)
    source = Column(Text, nullable=True)
